### ISSUE TITLE
can you provide the train data and vocabulary?

### ISSUE THREAD

**Issue by Lizhengo2** [ZhenYangIACAS/NMT_GAN#1]
can you provide the train data and vocabulary? I want to know the format of data

**Comment by kellymarchisio** [comment]
I believe you can get it here under Walkthrough: https://github.com/tensorflow/tensor2tensor

**Comment by ZhenYangIACAS** [comment]
No problem. We are so sorry that we did not give any samples for the training data and vocabulary. We will provide some data samples as soon as possible when we finished the holiday.

**Comment by ZhenYangIACAS** [comment]
We have provide the vocab file! The file for training data is simple, just one sentence in each line.

**Comment by rzhangpku** [comment]
But I cannot get the point of the data. Can you provide the train data in Google Drive? Thank you very much.
