### ISSUE TITLE
the difference between generating sample and sentence translation

### ISSUE THREAD

**Issue by jeicy07** [ZhenYangIACAS/NMT_GAN#13]
Hi, I notice that when generating samples, you just build a model for generation and feed data in it and calculate "generate_samples" directly. However, when translating sentences at the beginning of evaluation, you use beam search to translate, instead of using above models. I wonder why you use such different methods since in my opinion, generating samples and translation are the same tasks. Thanks!

**Comment by ZhenYangIACAS** [comment]
Yes, we use different methods for sample generation and evaluation. And we present the explanations about this in our paper. For sample generation, we simply use the greedy search because of its low cost of time. For evaluation, we use the beam search for its high accuracy.
