### ISSUE TITLE
Preprocessing of en2de data

### ISSUE THREAD

**Issue by zoharai** [ZhenYangIACAS/NMT_GAN#15]
Hi,
Can you upload your pre-processing script or add information about which scripts did you use?
For example, did you use true-casing, tokenization, removing weird characters, checking the sentence alignments ?

Thanks!

**Comment by ZhenYangIACAS** [comment]
All of the data we used is simply pre-processed by tokenization and BPE. For tokenization, we used the script in Mose. For BPE, we used the released subword-toolkit. We did not do anything  else for pre-processing.

**Comment by zoharai** [comment]
Thanks!

**Comment by zoharai** [comment]
Hi, 
Another question regarding the BPE:
Did you use learn_bpe.py script or learn_joint_bpe_and_vocab.py?
And, did you use the default number of merge operations (10000) or did you change it?

Thanks!
Zohar

**Comment by ZhenYangIACAS** [comment]
we used the learn_bpe.py and the number for merge operations is set as 30000.
