### ISSUE TITLE
How to get the vocab files？

### ISSUE THREAD

**Issue by luckper** [ZhenYangIACAS/NMT_GAN#18]
HI, the src_vocab and dst_vocab in vocab files with 38831/34432 words, is generated by how many pieces of data are generated separately for the vocab.py？
By vocab.py，The result has two columns of data, taking the first column as a vocabulary file？
Thanks～

**Comment by ZhenYangIACAS** [comment]
@luckper You mean the BPE merge operation? we set it as 32000. Actually, you can directly use the file generated by vocab.py as the vocabulary file. The second column has no effects on our program.

**Comment by luckper** [comment]
@ZhenYangIACAS Hi，I have a question，pre-processed the data by tokenization and BPE，about tokenization and BPE，How are you dealing with it ? Which scripts or tools are used?
Thanks～～

**Comment by ZhenYangIACAS** [comment]
@luckper You can find the answers in some one issue proposed by others.  I remember that some one has asked this question before and you are supposed to scan the existing issues before you propose a new issue. Anyway, we are still glad to answer this question again. For tokenization,  we utilize the script of Mose. And you can also use the nltk to do tokenization. For BPE, we utilize the open-source subword-nmt toolkit. You can find the download links easily.

**Comment by luckper** [comment]
@ZhenYangIACAS  First，thanks for your answer！
I have got the subword-nmt，and I am watching the subword-nmt.
But I can't understand the relationship between the tokenization and the BPE，and what are we tokenization? the word or sentence？
Thanks～～

**Comment by zoharai** [comment]
@ZhenYangIACAS  Hi, for English-German, did you use 32000 or 30000 BPE merge operations?

**Comment by ZhenYangIACAS** [comment]
30000 merge operations

**Comment by xixiddd** [comment]
> @luckper You mean the BPE merge operation? we set it as 32000. Actually, you can directly use the file generated by vocab.py as the vocabulary file. The second column has no effects on our program.

Hi, zhen yang, I would like to make some clarifications.

- for en-de, you learn the BPE code jointly with merge operation set to 32000
- you then apply the BPE to training corpus and get the source and target vocabularies, which contains 38831/34432 subword-units respectively

Moreover, I am confused that the `src_vocab_size` and `dst_vocab_size` are both 32000 in the _config_generator_train.yaml_  while in the other *.yaml (e.g. _config_generate_sample.yaml_), the  `src_vocab_size` and `dst_vocab_size` are set to 38831/34432 respectively.

Looking forward to your reply, many thanks.
