### ISSUE TITLE
Dropout

### ISSUE THREAD

**Issue by borgr** [ZhenYangIACAS/NMT_GAN#19]
Could you explain the dropout used? I see it is hardcoded to 1.0 (which means it is not used at all). Do you set it to something else when you run? do you have it in one of the config files?
Thanks

**Comment by ZhenYangIACAS** [comment]
@borgr You mean the dropout in the discriminator?  In the tensorflow API, the parameter means the probability of keeping the values. Therefore, 1.0 means that we did not use any dropout in our discriminator. However, you can test different values for the dropout.
