### ISSUE TITLE
Release RNNSearch model?

### ISSUE THREAD

**Issue by kellymarchisio** [ZhenYangIACAS/NMT_GAN#2]
Thanks for releasing this - I've enjoyed playing around with it.  Do you intend to release your RNNSearch generator code?  I imagine you've released only the Transformer code because it got better results (thank you!), but I'd enjoy comparing to your other published results gotten with RNNSearch. Thanks!

**Comment by ZhenYangIACAS** [comment]
Actually, the RNNsearch model is implemented the same with the open-source toolkit dl4mt. We just reconstruct it with tensorflow. Although I am in holiday, I will release our RNNsearch model as soon as possible.

**Comment by ZhenYangIACAS** [comment]
We have upload our code about the RNNsearch!

**Comment by kellymarchisio** [comment]
thanks so much!

**Comment by ZhenYangIACAS** [comment]
@kellymarchisio  that is all right. If you like our code,  you are expected to give a star for our contributions.
