### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by zhangzhen999** [ZhenYangIACAS/NMT_GAN#20]
Hi,
python2 /NMT_GAN-master/discriminator_pretrain.py

Traceback (most recent call last):
  File "/NMT_GAN-master/discriminator_pretrain.py", line 73, in <module>
    config = AttrDict(yaml.load(open(args.config)))
TypeError: coercing to Unicode: need string or buffer, NoneType found

Looking forward to your advice or answers.
Best regards,
Thank you very much!

**Comment by ZhenYangIACAS** [comment]
You need to run the discriminator_pretrain.py like this: "python discriminator_pretrain.py  -c ./configs/config_discriminator_pretrain.yaml". I guess the NoneType means that you didn't pass any value to the config parameter.

**Comment by zhangzhen999** [comment]
Thank you very much!
