### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by zhangzhen999** [ZhenYangIACAS/NMT_GAN#21]
Thank you very much for helping me solve the last question!
when I run "sh discriminator_pretrain.sh" ,
it gives the following error:
"Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ../experience/data_180w/dis_pretrain/model-180w_zh2en_bpe/dis_180w_bpe"

what should I do?
please give me some suggestions, thank you!

**Comment by ZhenYangIACAS** [comment]
Hi，you should change the file path as your own data path.
