### ISSUE TITLE
How to get the dis_negative_data in the config_discriminator_pretrain.yaml?

### ISSUE THREAD

**Issue by rzhangpku** [ZhenYangIACAS/NMT_GAN#25]
How to get the dis_negative_data in the config_discriminator_pretrain.yaml? Thank you very much!

**Comment by ZhenYangIACAS** [comment]
It has been described clearly in our paper. You should decode part of your training data with the pre-trained NMT model.

**Comment by rzhangpku** [comment]
Thank you very much.
