### ISSUE TITLE
Training data size for the generator and discriminator

### ISSUE THREAD

**Issue by QiushuiZzz** [ZhenYangIACAS/NMT_GAN#34]
I'm sorry to bother you after so many years:
1. I would be interested to know the size of the data used to pre-train the generator and the pre-train the discriminator on the zh-en data in the paper.
2. And whether the data used in **train:**, **generator:** and **discriminator:** during adversarial training in **config_gan_train.yaml** is the same as the data used in the previous pre-training of the generator and discriminator.
Looking forward to your reply

**Comment by ZhenYangIACAS** [comment]
Sorry for the late reply.  As so many years passed, I cannot answer such a detailed question.
